### PR TITLE
SVCPLAN-4678: lctl ping sudo for telegraf

### PR DESCRIPTION
**Pull request by jdmaloney**
@jakerundall (or someone else in ASD) Please review at your convenience

### CODE REVIEW

**Comment by jakerundall** [comment]
Similar here, go ahead and add a `@param` doc comment for the new parameter and rebuild the REFERENCE.md file and we should be good to go.

**Comment by jakerundall** [comment]
Also noting, this was tested on mgtest05.

**Comment by jdmaloney** [comment]
@jakerundall Thanks for the review that has been done

**Review by jakerundall — APPROVED** [review]
Looks good

**Pull request merged**
