### PR TITLE
Fixed parsing issues with regard to pools and rpcs

### PR DESCRIPTION
**Pull request by jdmaloney**
Ready for review; should fix RPC and QoS stats for Delta (better handling systems that have multiple Lustre file systems with different architectures).

### CODE REVIEW

**Review by jakerundall — APPROVED** [review]
Seems fine. Have you tested on Delta and on something simpler like MG?

**Comment by jdmaloney** [comment]
@jakerundall I've tested both on Delta (cn104) and Magnus (mg001); check is performing as expected.

One last clarifying questions; I see the pdk-validate checks failing.  Is that a known issue with those checks or should I be looking for an issue in my PR?

**Comment by jakerundall** [comment]
> One last clarifying questions; I see the pdk-validate checks failing. Is that a known issue with those checks or should I be looking for an issue in my PR?

There's definitely an issue with the check on GitHub (it can't pull down some Ruby Gem needed for the check). I can circle back and see if I can fix it separately.

**Comment by jdmaloney** [comment]
@jakerundall No worries, I don't think that needs to be a priority (or at least I won't be the one to imply it should be one).  I'll go ahead and merge this request.

**Pull request merged**
